Fatal Error: <<"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 104, in run\n    result = self.view_func(request, **values)\n  File \"/medical/apps/api/fhir/routers.py\", line 577, in get_package_medicinal_products\n    pmp_items = [pmp.as_fhir_detail() for pmp in paginate_objects.object_list.all()]\n  File \"/medical/apps/api/fhir/routers.py\", line 577, in <listcomp>\n    pmp_items = [pmp.as_fhir_detail() for pmp in paginate_objects.object_list.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 205, in as_fhir_detail\n    \"packaging\": [pic.as_pmp_fhir() for pic in self.packageitemcontainer_set.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 205, in <listcomp>\n    \"packaging\": [pic.as_pmp_fhir() for pic in self.packageitemcontainer_set.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 83, in as_pmp_fhir\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 83, in <listcomp>\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/organisation/models.py\", line 289, in as_fhir_v2\n    \"manufacturer\": {\"reference\": f\"Organization/{self.manufacturer.organisation_name}\"}\nAttributeError: 'NoneType' object has no attribute 'organisation_name'\n">>
00:20:54.468 [warn]  Page: 6/254/0

Fatal Error: <<"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 104, in run\n    result = self.view_func(request, **values)\n  File \"/medical/apps/api/fhir/routers.py\", line 577, in get_package_medicinal_products\n    pmp_items = [pmp.as_fhir_detail() for pmp in paginate_objects.object_list.all()]\n  File \"/medical/apps/api/fhir/routers.py\", line 577, in <listcomp>\n    pmp_items = [pmp.as_fhir_detail() for pmp in paginate_objects.object_list.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 205, in as_fhir_detail\n    \"packaging\": [pic.as_pmp_fhir() for pic in self.packageitemcontainer_set.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 205, in <listcomp>\n    \"packaging\": [pic.as_pmp_fhir() for pic in self.packageitemcontainer_set.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 83, in as_pmp_fhir\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 83, in <listcomp>\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/organisation/models.py\", line 289, in as_fhir_v2\n    \"manufacturer\": {\"reference\": f\"Organization/{self.manufacturer.organisation_name}\"}\nAttributeError: 'NoneType' object has no attribute 'organisation_name'\n">>
00:21:31.932 [warn]  Page: 15/254/0

Fatal Error: <<"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 104, in run\n    result = self.view_func(request, **values)\n  File \"/medical/apps/api/fhir/routers.py\", line 577, in get_package_medicinal_products\n    pmp_items = [pmp.as_fhir_detail() for pmp in paginate_objects.object_list.all()]\n  File \"/medical/apps/api/fhir/routers.py\", line 577, in <listcomp>\n    pmp_items = [pmp.as_fhir_detail() for pmp in paginate_objects.object_list.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 205, in as_fhir_detail\n    \"packaging\": [pic.as_pmp_fhir() for pic in self.packageitemcontainer_set.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 205, in <listcomp>\n    \"packaging\": [pic.as_pmp_fhir() for pic in self.packageitemcontainer_set.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 83, in as_pmp_fhir\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 83, in <listcomp>\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/organisation/models.py\", line 289, in as_fhir_v2\n    \"manufacturer\": {\"reference\": f\"Organization/{self.manufacturer.organisation_name}\"}\nAttributeError: 'NoneType' object has no attribute 'organisation_name'\n">>
00:28:33.695 [warn]  Page: 6/254/0

Fatal Error: <<"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 104, in run\n    result = self.view_func(request, **values)\n  File \"/medical/apps/api/fhir/routers.py\", line 577, in get_package_medicinal_products\n    pmp_items = [pmp.as_fhir_detail() for pmp in paginate_objects.object_list.all()]\n  File \"/medical/apps/api/fhir/routers.py\", line 577, in <listcomp>\n    pmp_items = [pmp.as_fhir_detail() for pmp in paginate_objects.object_list.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 205, in as_fhir_detail\n    \"packaging\": [pic.as_pmp_fhir() for pic in self.packageitemcontainer_set.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 205, in <listcomp>\n    \"packaging\": [pic.as_pmp_fhir() for pic in self.packageitemcontainer_set.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 83, in as_pmp_fhir\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 83, in <listcomp>\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/organisation/models.py\", line 289, in as_fhir_v2\n    \"manufacturer\": {\"reference\": f\"Organization/{self.manufacturer.organisation_name}\"}\nAttributeError: 'NoneType' object has no attribute 'organisation_name'\n">>
00:29:11.895 [warn]  Page: 15/254/0

Fatal Error: <<"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 104, in run\n    result = self.view_func(request, **values)\n  File \"/medical/apps/api/fhir/routers.py\", line 577, in get_package_medicinal_products\n    pmp_items = [pmp.as_fhir_detail() for pmp in paginate_objects.object_list.all()]\n  File \"/medical/apps/api/fhir/routers.py\", line 577, in <listcomp>\n    pmp_items = [pmp.as_fhir_detail() for pmp in paginate_objects.object_list.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 205, in as_fhir_detail\n    \"packaging\": [pic.as_pmp_fhir() for pic in self.packageitemcontainer_set.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 205, in <listcomp>\n    \"packaging\": [pic.as_pmp_fhir() for pic in self.packageitemcontainer_set.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 83, in as_pmp_fhir\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 83, in <listcomp>\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/organisation/models.py\", line 289, in as_fhir_v2\n    \"manufacturer\": {\"reference\": f\"Organization/{self.manufacturer.organisation_name}\"}\nAttributeError: 'NoneType' object has no attribute 'organisation_name'\n">>
00:31:18.449 [warn]  Page: 47/254/0

Fatal Error: <<"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 104, in run\n    result = self.view_func(request, **values)\n  File \"/medical/apps/api/fhir/routers.py\", line 577, in get_package_medicinal_products\n    pmp_items = [pmp.as_fhir_detail() for pmp in paginate_objects.object_list.all()]\n  File \"/medical/apps/api/fhir/routers.py\", line 577, in <listcomp>\n    pmp_items = [pmp.as_fhir_detail() for pmp in paginate_objects.object_list.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 205, in as_fhir_detail\n    \"packaging\": [pic.as_pmp_fhir() for pic in self.packageitemcontainer_set.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 205, in <listcomp>\n    \"packaging\": [pic.as_pmp_fhir() for pic in self.packageitemcontainer_set.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 83, in as_pmp_fhir\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 83, in <listcomp>\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/organisation/models.py\", line 289, in as_fhir_v2\n    \"manufacturer\": {\"reference\": f\"Organization/{self.manufacturer.organisation_name}\"}\nAttributeError: 'NoneType' object has no attribute 'organisation_name'\n">>
00:31:47.187 [warn]  Page: 54/254/0

Fatal Error: <<"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 105, in run\n    return self._result_to_response(request, result, temporal_response)\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 202, in _result_to_response\n    result = response_model.from_orm(resp_object).dict(\n  File \"/usr/local/lib/python3.7/site-packages/ninja/schema.py\", line 164, in from_orm\n    return super().from_orm(obj)\n  File \"pydantic/main.py\", line 574, in pydantic.main.BaseModel.from_orm\npydantic.error_wrappers.ValidationError: 12 validation errors for NinjaResponseSchema\nresponse -> items -> 1 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 1 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 1 -> packaging -> 0 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 1 -> packaging -> 1 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 1 -> packaging -> 1 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 1 -> packaging -> 2 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 2 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 2 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 2 -> packaging -> 0 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 2 -> packaging -> 1 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 2 -> packaging -> 1 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 2 -> packaging -> 2 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\n">>
00:49:14.224 [warn]  Page: 175/254/0

Fatal Error: <<"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 105, in run\n    return self._result_to_response(request, result, temporal_response)\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 202, in _result_to_response\n    result = response_model.from_orm(resp_object).dict(\n  File \"/usr/local/lib/python3.7/site-packages/ninja/schema.py\", line 164, in from_orm\n    return super().from_orm(obj)\n  File \"pydantic/main.py\", line 574, in pydantic.main.BaseModel.from_orm\npydantic.error_wrappers.ValidationError: 8 validation errors for NinjaResponseSchema\nresponse -> items -> 16 -> packaging -> 1 -> packaging -> 0 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 16 -> packaging -> 2 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 17 -> packaging -> 0 -> packaging -> 0 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 17 -> packaging -> 1 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 18 -> packaging -> 0 -> packaging -> 0 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 18 -> packaging -> 1 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 19 -> packaging -> 0 -> packaging -> 0 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 19 -> packaging -> 1 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\n">>
00:54:20.436 [warn]  Page: 217/254/0

Fatal Error: <<"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 105, in run\n    return self._result_to_response(request, result, temporal_response)\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 202, in _result_to_response\n    result = response_model.from_orm(resp_object).dict(\n  File \"/usr/local/lib/python3.7/site-packages/ninja/schema.py\", line 164, in from_orm\n    return super().from_orm(obj)\n  File \"pydantic/main.py\", line 574, in pydantic.main.BaseModel.from_orm\npydantic.error_wrappers.ValidationError: 20 validation errors for NinjaResponseSchema\nresponse -> items -> 0 -> packaging -> 0 -> packaging -> 0 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 0 -> packaging -> 1 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 1 -> packaging -> 0 -> packaging -> 0 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 1 -> packaging -> 1 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 2 -> packaging -> 0 -> packaging -> 0 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 2 -> packaging -> 1 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 3 -> packaging -> 0 -> packaging -> 0 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 3 -> packaging -> 1 -> containedItem -> 0 -> item -> amount -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 11 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 11 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 11 -> packaging -> 0 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 11 -> packaging -> 1 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 11 -> packaging -> 1 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 11 -> packaging -> 2 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 12 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 12 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 12 -> packaging -> 0 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 12 -> packaging -> 1 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 12 -> packaging -> 1 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 12 -> packaging -> 2 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\n">>
00:54:28.598 [warn]  Page: 218/254/0

Fatal Error: <<"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 105, in run\n    return self._result_to_response(request, result, temporal_response)\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 202, in _result_to_response\n    result = response_model.from_orm(resp_object).dict(\n  File \"/usr/local/lib/python3.7/site-packages/ninja/schema.py\", line 164, in from_orm\n    return super().from_orm(obj)\n  File \"pydantic/main.py\", line 574, in pydantic.main.BaseModel.from_orm\npydantic.error_wrappers.ValidationError: 24 validation errors for NinjaResponseSchema\nresponse -> items -> 15 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 15 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 15 -> packaging -> 0 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 15 -> packaging -> 1 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 15 -> packaging -> 1 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 15 -> packaging -> 2 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 16 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 16 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 16 -> packaging -> 1 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 17 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 17 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 17 -> packaging -> 1 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 18 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 18 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 18 -> packaging -> 0 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 18 -> packaging -> 1 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 18 -> packaging -> 1 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 18 -> packaging -> 2 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 19 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 19 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 19 -> packaging -> 0 -> packaging -> 0 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 19 -> packaging -> 1 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 19 -> packaging -> 1 -> packaging -> 0 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\nresponse -> items -> 19 -> packaging -> 2 -> shellLifeStorage -> 0 -> period -> value\n  none is not an allowed value (type=type_error.none.not_allowed)\n">>
00:56:40.393 [warn]  Page: 237/254/0

