Fatal Error: <<"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/ninja/operation.py\", line 104, in run\n    result = self.view_func(request, **values)\n  File \"/medical/apps/api/fhir/routers.py\", line 247, in get_manufactured_items\n    manufactured_items = [mfi.as_fhir() for mfi in paginate_mfi.object_list.all()]\n  File \"/medical/apps/api/fhir/routers.py\", line 247, in <listcomp>\n    manufactured_items = [mfi.as_fhir() for mfi in paginate_mfi.object_list.all()]\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 846, in as_fhir\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/medicinalproduct/models/package.py\", line 846, in <listcomp>\n    \"manufacturer\": [manufacturer.as_fhir_v2() for manufacturer in self.manufacturers.all()],\n  File \"/medical/apps/organisation/models.py\", line 289, in as_fhir_v2\n    \"manufacturer\": {\"reference\": f\"Organization/{self.manufacturer.organisation_name}\"}\nAttributeError: 'NoneType' object has no attribute 'organisation_name'\n">>
01:23:55.941 [warn]  Page: 1/0/50

01:23:57.489 [warn]  Page: 0/0/35
